//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BodyNote.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BODYNOTE_DIALOG             102
#define IDR_HTML_ADDDOCUMENTDLG         103
#define IDR_HTML_ADDDOCUMENTDLG1        105
#define IDR_MAINFRAME                   128
#define IDI_ICON_ADDNOTE                129
#define IDI_ICON_ADDNOTEG               130
#define IDI_ICON_UNDO                   131
#define IDI_ICON_UNDOG                  132
#define IDI_ICON_SHOT                   133
#define IDI_ICON_SHOTG                  134
#define IDI_ICON_CANCEL                 135
#define IDI_ICON_CANCELG                136
#define IDI_ICON_EXIT                   137
#define IDI_ICON_EXITG                  138
#define IDI_ICON_OPEN                   139
#define IDI_ICON_OPENG                  140
#define IDI_ICON_TUTORIAL               141
#define IDI_ICON_TUTORIALG              142
#define IDI_ICON_ABOUT                  143
#define IDI_ICON_ABOUTG                 144
#define IDI_ICON_START                  145
#define IDI_ICON_STOP                   146
#define IDD_DIALOG_LOADRECORD           147
#define IDD_DIALOG_SETTINGS             148
#define IDD_DIALOG1                     149
#define IDD_DIALOG_ACCESSPSW            149
#define IDI_ICON_SETTINGS               150
#define IDI_ICON_SETTINGSG              151
#define IDI_ICON_STARTG                 152
#define IDI_ICON_STOPG                  153
#define IDI_ICON_ADD                    154
#define IDI_ICON_ADDG                   155
#define IDI_ICON_REMOVE                 156
#define IDI_ICON_REMOVEG                157
#define IDI_ICON_LOAD                   158
#define IDI_ICON_LOADG                  159
#define IDR_MENU1                       160
#define IDR_MENU_IO                     160
#define IDD_DIALOG_MOREDATA             161
#define IDI_ICON_DETAIL                 162
#define IDI_ICON_DETAILG                163
#define IDD_RULERRICHEDITCTRLDEMO_DIALOG 165
#define IDI_ICON_ADDDOC                 166
#define IDI_ICON_ADDDOCG                167
#define IDI_ICON_VIEWDOC                168
#define IDI_ICON_VIEWDOCG               169
#define IDD_DIALOG_ADDDOCUMENT          170
#define IDD_DIALOG_LOADDOC              171
#define IDD_DIALOG_BACKUPPROGRESS       172
#define IDC_STATIC_CAM1                 1000
#define IDC_BUTTON_STARTWEBCAM          1001
#define IDC_STATIC_PLACEMENT            1001
#define IDC_BUTTON_STOPWEBCAM           1002
#define IDC_STATIC_CAM2                 1005
#define IDC_STATIC_CAM3                 1006
#define IDC_STATIC_CURCAMPIC            1007
#define IDC_BUTTON_SAVERTF              1007
#define IDC_CHECK_CAM1                  1008
#define IDC_CHECK_CAM2                  1009
#define IDC_BUTTON_LOADRTF              1009
#define IDC_CHECK_CAM3                  1010
#define IDC_STATIC_CURCAMTITLE          1011
#define IDC_BUTTON_SHOT                 1012
#define IDC_BUTTON_NEWRTF               1012
#define IDC_BUTTON_ABOUT                1013
#define IDC_CHECK_SHOW_TOOLBAR          1013
#define IDC_BUTTON_NEW                  1014
#define IDC_CHECK_SHOW_RULER            1014
#define IDC_BUTTON_LOAD                 1015
#define IDC_BUTTON_SAVE                 1016
#define IDC_BUTTON_DELETE               1016
#define IDC_CHECK_READONLY              1016
#define IDC_EDIT_NAME                   1018
#define IDC_EDIT_SURNAME                1019
#define IDC_DATETIMEPICKER              1020
#define IDC_EDIT_AGE                    1021
#define IDC_EDIT_VISITCAUSE             1022
#define IDC_EDIT_COMMENT                1023
#define IDC_EDIT_DIAGNOSIS              1024
#define IDC_COMBO_PICTURES              1025
#define IDC_EDIT_PHONE                  1026
#define IDC_EDIT_EMAIL                  1027
#define IDC_BUTTON_OPENPATIENTFOLDER    1029
#define IDC_CHECK_EDITDATA              1032
#define IDC_BUTTON_DELETEPICTURE        1033
#define IDC_LIST_PATIENTS               1034
#define IDC_EDIT_BIRTHDATE              1035
#define IDC_BUTTON_DELPATIENT           1037
#define IDC_BUTTON_SETTINGS             1038
#define IDC_BUTTON_PICKFOLDER           1038
#define IDC_EDIT_WROKSPACEFOLDER        1039
#define IDC_EDIT_PW1                    1040
#define IDC_EDIT_PW2                    1041
#define IDC_EDIT_PSW                    1042
#define IDC_CHECK_SHOTSOUND             1043
#define IDC_STATIC_VER                  1044
#define IDC_STATIC_RECORDFOUND          1045
#define IDC_EDIT_MOTIVOCONSULTO         1046
#define IDC_EDIT_INSORGENZASINTOMI      1048
#define IDC_EDIT_CARATTERISTICHESINTOMO 1049
#define IDC_EDIT_TERAPIEPRECEDENTI      1050
#define IDC_EDIT_CARDIORESPIRATORIO     1051
#define IDC_EDIT_CARDIOINTESTINALE      1052
#define IDC_EDIT_UROGENITALE            1053
#define IDC_EDIT_RESPIRATORIO           1054
#define IDC_EDIT_ESAMIDIAGNOSTICI       1055
#define IDC_EDIT_USOFARMACI             1056
#define IDC_EDIT_ALIMENTAZIONE          1057
#define IDC_EDIT_VARIAZIONEPESO         1058
#define IDC_EDIT_SONNOSVEGLIA           1059
#define IDC_EDIT_CEFALEE                1060
#define IDC_EDIT_SPORT                  1061
#define IDC_EDIT_INTERVENTI             1062
#define IDC_EDIT_GRAVIDANZE             1063
#define IDC_EDIT_MALATTIEIMPORTANTI     1064
#define IDC_EDIT_VALUTAZIONEFAMILIARE   1065
#define IDC_EDIT_PROFESSIONE            1066
#define IDC_EDIT_TRAUMATISMI            1067
#define IDC_EDIT_HOBBY                  1068
#define IDC_EDIT_VISTA                  1069
#define IDC_EDIT_DIAGNOSI               1071
#define IDC_BUTTON_MOREDETAILS          1072
#define IDC_EDIT_CAUSASCATENANTE        1072
#define IDC_EDIT_STOMATOGNATICO         1073
#define IDC_EDIT_CICATRICI              1074
#define IDC_EDIT_MICROGALVANISMI        1075
#define IDC_EDIT_BILANCIOPOSTURALE      1076
#define IDC_EDIT_CHINESIOLOGICI         1077
#define ID_BUTTON_OK                    1087
#define IDC_EDIT_PELLE                  1089
#define IDC_BUTTON_DIARIO               1090
#define IDC_BUTTON_CARICADOC            1091
#define IDC_EDIT_ALTRO                  1091
#define IDC_BUTTON_VEDIDOC              1092
#define IDC_EDIT1                       1093
#define IDC_EDIT_SELECTEDPATH           1093
#define IDC_EDIT_SEARCH                 1093
#define IDC_BUTTON_ADD                  1094
#define IDC_EDIT_NEWNAME                1095
#define IDC_DATETIMEPICKER1             1096
#define IDC_BUTTON_OPEN                 1097
#define IDC_PROGRESS_LOADARCHIVE        1099
#define IDC_CHECK_BACKWEEK              1100
#define IDC_CHECK_BACKMONTH             1101
#define IDC_PROGRESS_BACK               1102
#define ID_INPUT_INPUTDATA              32771
#define ID_INPUT_EXPORT                 32772
#define ID_INPUT_BACKUPARCHIVIO         32773
#define ID_DBTOOLS_AGGIORNADB           32774
#define ID_GESTIONEARCHIVIO_INPUTDAALTROWORKSPACE 32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
